baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Nomads Mod"
theme = "vex-hugo"

[params]
  favicon = ""
  site_logo = "./img/nomads-logo.png"
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-white"
  featured_image = "img/nomads-hero-image.jpg"
  featured_hero_image = "img/Render_02.png"

  recent_posts_number = 2
  custom_css = ["css/nomads.css"]
  body_classes = "avenir "